language: php

php:
  - 5.6
  - 7.0

env:
  - NODEJS_VERSION=6.10.2

before_script:
  - cp .env.example .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - nvm install $NODEJS_VERSION
  - npm install
  - php artisan key:generate
  - bower install
  - npm run dev
  - php artisan migrate --seed --no-interaction
  #- php -S localhost:8080 -t public/

script:
  - vendor/bin/phpunit
